### Swap cats
POST http://localhost:8080/odata/v4/AnimalsService/Users(571ba148-4654-4830-9c1c-f25b97957f8a)/testAction
Content-Type: application/json

{
    "firstId" : "308e71dd-8e81-44d1-b273-9e9ae318bf82", 
    "secondId" : "5a379566-c05f-453f-b59c-6df73647395c"
}

### Add Vlad user
POST http://localhost:8080/odata/v4/AnimalsService/Users
Content-Type: application/json

{
    "name": "Vlad"
}
### id : 35febf21-9f2c-4988-8822-9f36e91acd56

### Add Nom user
POST http://localhost:8080/odata/v4/AnimalsService/Users
Content-Type: application/json

{
    "name": "Nom"
}
### id : df7831db-2f7f-44ca-9c7d-80f05b41593b

### Add cats for Nom
POST http://localhost:8080/odata/v4/AnimalsService/Cats
Content-Type: application/json

{
    "name": "NomCat2",
    "owner_ID" : "df7831db-2f7f-44ca-9c7d-80f05b41593b",
    "catbreed" : "someCatBreed2"
}

### Add dogs for Nom
POST http://localhost:8080/odata/v4/AnimalsService/Dogs
Content-Type: application/json

{
  "name": "NomDog1",
  "owner_ID" : "df7831db-2f7f-44ca-9c7d-80f05b41593b",
  "dogbreed" : "someDogBreed1"
}

### Add cat for Vlad
POST http://localhost:8080/odata/v4/AnimalsService/Cats
Content-Type: application/json

{
    "name": "VladCat",
    "owner_ID" : "71f1941d-d2e6-4e38-bef0-3e904c032e39",
    "catbreed" : "bread"
}


### Add cat for Vlad
POST http://localhost:8080/odata/v4/AnimalsService/Dogs
Content-Type: application/json

{
  "name": "NomDog1",
  "owner_ID" : "9c4452dd-5483-4006-bf00-8d5370c2aa24",
  "dogbreed" : "someDogBread1"
}