---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/Cap/AnimalsService/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1