---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/Cap/AnimalsService/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1

cds:
  security:
    mock:
      users:
        - name: auth-user
          password: auth-pass
          roles:
            - auth-role
          additional:
           email: auth-user@email.com
